# Change these first
owner: MichaelVeevaPay # Your GitHub organization or username, where this repository lives
repo: Trust.VeevaTools # The name of this repository

sites:
  - name: VeevaTools Production
    url: https://cctools.veevaservices.com
  - name: VeevaTools Deveveloper
    url: https://cctools-dev.veevaservices.com
  - name: VeevaTools Production - API
    url: https://cctools-api.veevaservices.com
  - name: VeevaTools Developer - API
    url: https://cctools-dev-api.veevaservices.com

status-website:

  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Trust.VeevaTools
  logoUrl: https://raw.githubusercontent.com/MichaelVeevaPay/Trust.VeevaTools/master/assets/VeevaTools-04.png
  name: VeevaTools Trust
  introTitle: "VeevaTools Service Statuses"
  introMessage: This page contains the statues of all Veeva Tools sites.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: Veeva Tools
